apiVersion: apps/v1
kind: Deployment

metadata:
  name: signalrservice-deployment
  namespace: dev
  labels:
    run: signalrservice

spec:
  replicas: 1
  selector:
    matchLabels:
      run: signalrservice
  
  template:
    metadata:
      labels:
        run: signalrservice
    spec:
      containers:
      - name: signalrservice-container
        image: local/logcorner-edusync-signalr-server:1.0.1
        imagePullPolicy: Never
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Kubernetes"
        ports:
        - containerPort: 80
          protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
    