apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka
spec:
  selector:
    name: strimzi-cluster-operator
  ports:
    - name: kafka
      protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: 30637 
  type: NodePort
