version: '3.4'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: on-failure
    ports:
      - '9090:9090'
    volumes:
      - /path/to/prometheus/config:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    restart: on-failure
    ports:
      - 9412:9411
    # networks:
    #   - speech_network

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    restart: on-failure
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686
    depends_on:
      - zipkin
    # networks:
    #   - speech_network
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
        - "2181:2181"
  
  kafka:
    image: wurstmeister/kafka
    ports:
        - "9092:9092"
    environment:
        KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
        KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
        KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
        - zookeeper
# networks:
#   speech_network:
#     external: true
      

