apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
  namespace: helm
  labels:
    product: {{ .Release.Name }}-{{ .Chart.Name }}
    environment: helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}-producer
      env: helm
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}-producer
        env: helm
    spec:
      containers:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}-producer
          image: logcornerhub/logcorner-edusync-speech-producer
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Kubernetes.helm"
            
