apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
  #namespace: qa
  labels:
    version: 1.0.0
    product: kibana
    environment: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
      env: qa
  template:
    metadata:
      labels:
        app: kibana
        env: qa
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.13.1
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch:9200
        ports:
        - containerPort: 5601
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  #namespace: qa
  labels:
    name: kib-auto
spec:
  selector:
     app: kibana
     env: qa
  type: NodePort
  ports:
    - nodePort: 30001
      port: 5601
      protocol: TCP
      targetPort: 5601