version: '3.4'
services:
  logcorner.edusync.speech.producer:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
 
  logcorner.edusync.speech.consumer:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker