version: '3.4'

services:
  logcorner.edusync.speech.projection.workerservice:
    image: ${DOCKER_REGISTRY-}/logcorner-edusync-speech-worker
    build:
      context: .
      dockerfile: LogCorner.EduSync.Speech.Projection.WorkerService/Dockerfile
