apiVersion: apps/v1beta1
# kind: StatefulSet
kind: Deployment
metadata:
  name: elk-deployment
  namespace: dev
spec:
  # serviceName: elk
  # replicas: 3
  replicas: 1  
  template:
    metadata:
      labels:
        app: elk
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
      # init-container for setting the mmap count limit
      - name: sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:        
      - name: elk-container
        image: sebp/elk
        resources:
          requests:
            memory: "2Gi"
          limits:
            memory: "3Gi"
        ports:
          - name: elasticsearch
            protocol: TCP
            containerPort: 9200
          - name: kibana
            protocol: TCP
            containerPort: 5601
          - name: logstash
            protocol: TCP
            containerPort: 5044
        imagePullPolicy: Always