kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: dev
  labels:
    version: 1.0.0
    product: elasticsearch
    environment: dev
spec:
  selector:
    app: elasticsearch-node
    env: dev
  clusterIP: None
  ports:
    - port: 9200
      name: client-node
    - port: 9300
      name: inter-node