apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: dev
  labels:
    version: 1.0.0
    product: kibana
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
      env: dev
  template:
    metadata:
      labels:
        app: kibana
        env: dev
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.13.1
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch:9200
        ports:
        - containerPort: 5601