apiVersion: v1

kind: Service

metadata:
  name: rabbitmq-elk-processor
  namespace: dev

spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8092
      targetPort: 8092
  selector:
    app: rabbitmq-elk-processor